// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8aSXgLkH_PVoF0-lzrzzxDlA8BIVlIuM',
    appId: '1:607824099473:web:288d35d1fd3ba905737cd2',
    messagingSenderId: '607824099473',
    projectId: 'palpnote',
    authDomain: 'palp-5-latihan-firebase.firebaseapp.com',
    storageBucket: 'palpnote.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz4QmGUtEc3dyZFhK2AGFP6SalS9GcEs0',
    appId: '1:607824099473:android:224e8c19981f230a737cd2',
    messagingSenderId: '607824099473',
    projectId: 'palpnote',
    storageBucket: 'palpnote.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzcLnpEeE6IJnCMqBNP-exaEBtNH4hnlg',
    appId: '1:607824099473:android:40115bf7db3b57daea6730',
    messagingSenderId: '607824099473',
    projectId: 'palpnote',
    storageBucket: 'palpnote.firebasestorage.app',
    iosBundleId: 'com.example.palp5Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzcLnpEeE6IJnCMqBNP-exaEBtNH4hnlg',
    appId: '1:607824099473:android:40115bf7db3b57daea6730',
    messagingSenderId: '607824099473',
    projectId: 'palpnote',
    storageBucket: 'palpnote.firebasestorage.app',
    iosBundleId: 'com.example.palp5Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8aSXgLkH_PVoF0-lzrzzxDlA8BIVlIuM',
    appId: '1:607824099473:web:3166791eef02bf50737cd2',
    messagingSenderId: '607824099473',
    projectId: 'palpnote',
    authDomain: 'palp-5-latihan-firebase.firebaseapp.com',
    storageBucket: 'palpnote.firebasestorage.app',
  );
}
